sudo: required
services:
  - docker

before_install:
  - docker build -t demolt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true demolt/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-891376959231"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
